public class Constants {

	// BoltErrorLogger
	public static final String SOURCE_TYPE_APEX = 'Apex';
	public static final String SEVERITY_ERROR = 'ERROR';

	// Design Revision
	public static final String DESIGN_REVISION_HANDLER_NAME = 'DesignRevisionTriggerHandler';
	public static final String DESIGN_REVISION_STATUS_NOT_STARTED = 'Not Started';
	public static final String DESIGN_REVISION_NAME_PREFIX = 'REV';
	public static final String DESIGN_REVISION_NAME_DEFAULT_NUMBER = 'REV00';
	public static final String DESIGN_REVISION_UNKNOWN_ACCOUNT = 'Unknown';
	public static final String DESIGN_REVISION_RECORD_URL_BASE = '/lightning/r/Design_Revision__c/';
	public static final String RECORD_URL_VIEW_SUFFIX = '/view';
}
